server:
  port: 9003
spring:
  redis:
    pool:
      max-idle: 10
      min-idle: 5
      max-wait: 2000
      max-active: 10
    timeout: 2000
    host: 127.0.0.1
    port: 6379
  cache:
    cache-names: redisCache
    type: REDIS
    redis:
      time-to-live: 600000
